CREATE TABLE Utilisateur (Id INTEGER NOT NULL, Utilisateur_Type VARCHAR(31), Login VARCHAR(255), Password VARCHAR(255), ROLE VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE CENTRE (Id INTEGER NOT NULL, Adresse VARCHAR(255), Code_Postal VARCHAR(255), Email VARCHAR(255), Nom VARCHAR(255), Telephone VARCHAR(255), Ville VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE ClasseChimique (Id INTEGER NOT NULL, nom VARCHAR(255), mere INTEGER, PRIMARY KEY (Id))
CREATE TABLE ClassePharmacologique (Id INTEGER NOT NULL, nom VARCHAR(255), mere INTEGER, PRIMARY KEY (Id))
CREATE TABLE Departement (Numero VARCHAR(255) NOT NULL, Nom VARCHAR(255), Centre INTEGER, PRIMARY KEY (Numero))
CREATE TABLE EffetIndesirable (Id INTEGER NOT NULL, nom VARCHAR(255), pere INTEGER, PRIMARY KEY (Id))
CREATE TABLE LABORATOIRE (Id INTEGER NOT NULL, Adresse VARCHAR(255), Code_Postal VARCHAR(255), Email VARCHAR(255), Nom VARCHAR(255), Telephone VARCHAR(255), Ville VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE MEDECIN (Id INTEGER NOT NULL, Adresse VARCHAR(255), Code_Postal VARCHAR(255), Email VARCHAR(255), Lieu_travail VARCHAR(255), Nom VARCHAR(255), Prenom VARCHAR(255), Qualification VARCHAR(255), Telephone VARCHAR(255), Ville VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE ProduitMedical (Id INTEGER NOT NULL, Produit_Medical_Type VARCHAR(31), Nom VARCHAR(255), laboratoire INTEGER, PRIMARY KEY (Id))
CREATE TABLE MEDICAMENT (Id INTEGER NOT NULL, Contre_Indications VARCHAR(255), Indications VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE PATIENT (Id INTEGER NOT NULL, Adresse VARCHAR(255), Code_Postal VARCHAR(255), Date_Naissance VARCHAR(255), Email VARCHAR(255), Nom VARCHAR(255), Prenom VARCHAR(255), Telephone VARCHAR(255), Ville VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE SubstanceActive (Id INTEGER NOT NULL, Nom VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE Declaration (Id INTEGER NOT NULL, Poids FLOAT, EffetIndesirable INTEGER, ProduitMedical INTEGER, Utilisateur INTEGER, PRIMARY KEY (Id))
CREATE TABLE DISPOSITIFMEDICAL (Id INTEGER NOT NULL, RISQUE VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE Ingredient (Id INTEGER NOT NULL, Nom VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE PRODUITCOSMETIQUE (Id INTEGER NOT NULL, Contre_Indications VARCHAR(255), Indications VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE ClasseChimique_EffetIndesirable (Id_ClasseChimique INTEGER NOT NULL, Id_Id_EffetIndesirable INTEGER NOT NULL, PRIMARY KEY (Id_ClasseChimique, Id_Id_EffetIndesirable))
CREATE TABLE ClasseChimique_SubstanceActive (Id_ClasseChimique INTEGER NOT NULL, Id_SubstanceActive INTEGER NOT NULL, PRIMARY KEY (Id_ClasseChimique, Id_SubstanceActive))
CREATE TABLE ClassePharmacologique_EffetIndesirable (Id_ClassePharmacologique INTEGER NOT NULL, Id_Id_EffetIndesirable INTEGER NOT NULL, PRIMARY KEY (Id_ClassePharmacologique, Id_Id_EffetIndesirable))
CREATE TABLE ClassePharmacologique_SubstanceActive (Id_ClassePharmacologique INTEGER NOT NULL, Id_SubstanceActive INTEGER NOT NULL, PRIMARY KEY (Id_ClassePharmacologique, Id_SubstanceActive))
CREATE TABLE EffetIndesirable_ProduitMedical (Id_EffetIndesirable INTEGER NOT NULL, Id_ProduitMedical INTEGER NOT NULL, PRIMARY KEY (Id_EffetIndesirable, Id_ProduitMedical))
CREATE TABLE Medicament_SubstanceActive (Id_Medicament INTEGER NOT NULL, Id_SubstanceActive INTEGER NOT NULL, PRIMARY KEY (Id_Medicament, Id_SubstanceActive))
CREATE TABLE Patient_ProduitMedical (Id_Patient INTEGER NOT NULL, Id_ProduitMedical INTEGER NOT NULL, PRIMARY KEY (Id_Patient, Id_ProduitMedical))
CREATE TABLE Ingredient_ProduitCosmetique (Id_Ingredient INTEGER NOT NULL, Id_ProduitCosmetique INTEGER NOT NULL, PRIMARY KEY (Id_Ingredient, Id_ProduitCosmetique))
ALTER TABLE CENTRE ADD CONSTRAINT FK_CENTRE_Id FOREIGN KEY (Id) REFERENCES Utilisateur (Id)
ALTER TABLE ClasseChimique ADD CONSTRAINT FK_ClasseChimique_mere FOREIGN KEY (mere) REFERENCES ClasseChimique (Id)
ALTER TABLE ClassePharmacologique ADD CONSTRAINT FK_ClassePharmacologique_mere FOREIGN KEY (mere) REFERENCES ClasseChimique (Id)
ALTER TABLE Departement ADD CONSTRAINT FK_Departement_Centre FOREIGN KEY (Centre) REFERENCES Utilisateur (Id)
ALTER TABLE EffetIndesirable ADD CONSTRAINT FK_EffetIndesirable_pere FOREIGN KEY (pere) REFERENCES EffetIndesirable (Id)
ALTER TABLE LABORATOIRE ADD CONSTRAINT FK_LABORATOIRE_Id FOREIGN KEY (Id) REFERENCES Utilisateur (Id)
ALTER TABLE MEDECIN ADD CONSTRAINT FK_MEDECIN_Id FOREIGN KEY (Id) REFERENCES Utilisateur (Id)
ALTER TABLE ProduitMedical ADD CONSTRAINT FK_ProduitMedical_laboratoire FOREIGN KEY (laboratoire) REFERENCES Utilisateur (Id)
ALTER TABLE MEDICAMENT ADD CONSTRAINT FK_MEDICAMENT_Id FOREIGN KEY (Id) REFERENCES ProduitMedical (Id)
ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_Id FOREIGN KEY (Id) REFERENCES Utilisateur (Id)
ALTER TABLE Declaration ADD CONSTRAINT FK_Declaration_EffetIndesirable FOREIGN KEY (EffetIndesirable) REFERENCES EffetIndesirable (Id)
ALTER TABLE Declaration ADD CONSTRAINT FK_Declaration_Utilisateur FOREIGN KEY (Utilisateur) REFERENCES Utilisateur (Id)
ALTER TABLE Declaration ADD CONSTRAINT FK_Declaration_ProduitMedical FOREIGN KEY (ProduitMedical) REFERENCES ProduitMedical (Id)
ALTER TABLE DISPOSITIFMEDICAL ADD CONSTRAINT FK_DISPOSITIFMEDICAL_Id FOREIGN KEY (Id) REFERENCES ProduitMedical (Id)
ALTER TABLE PRODUITCOSMETIQUE ADD CONSTRAINT FK_PRODUITCOSMETIQUE_Id FOREIGN KEY (Id) REFERENCES ProduitMedical (Id)
ALTER TABLE ClasseChimique_EffetIndesirable ADD CONSTRAINT FK_ClasseChimique_EffetIndesirable_Id_Id_EffetIndesirable FOREIGN KEY (Id_Id_EffetIndesirable) REFERENCES EffetIndesirable (Id)
ALTER TABLE ClasseChimique_EffetIndesirable ADD CONSTRAINT FK_ClasseChimique_EffetIndesirable_Id_ClasseChimique FOREIGN KEY (Id_ClasseChimique) REFERENCES ClasseChimique (Id)
ALTER TABLE ClasseChimique_SubstanceActive ADD CONSTRAINT FK_ClasseChimique_SubstanceActive_Id_SubstanceActive FOREIGN KEY (Id_SubstanceActive) REFERENCES SubstanceActive (Id)
ALTER TABLE ClasseChimique_SubstanceActive ADD CONSTRAINT FK_ClasseChimique_SubstanceActive_Id_ClasseChimique FOREIGN KEY (Id_ClasseChimique) REFERENCES ClasseChimique (Id)
ALTER TABLE ClassePharmacologique_EffetIndesirable ADD CONSTRAINT ClassePharmacologique_EffetIndesirable_Id_ClassePharmacologique FOREIGN KEY (Id_ClassePharmacologique) REFERENCES ClassePharmacologique (Id)
ALTER TABLE ClassePharmacologique_EffetIndesirable ADD CONSTRAINT ClassePharmacologique_EffetIndesirable_Id_Id_EffetIndesirable FOREIGN KEY (Id_Id_EffetIndesirable) REFERENCES EffetIndesirable (Id)
ALTER TABLE ClassePharmacologique_SubstanceActive ADD CONSTRAINT ClassePharmacologique_SubstanceActive_Id_ClassePharmacologique FOREIGN KEY (Id_ClassePharmacologique) REFERENCES ClassePharmacologique (Id)
ALTER TABLE ClassePharmacologique_SubstanceActive ADD CONSTRAINT FK_ClassePharmacologique_SubstanceActive_Id_SubstanceActive FOREIGN KEY (Id_SubstanceActive) REFERENCES SubstanceActive (Id)
ALTER TABLE EffetIndesirable_ProduitMedical ADD CONSTRAINT FK_EffetIndesirable_ProduitMedical_Id_ProduitMedical FOREIGN KEY (Id_ProduitMedical) REFERENCES ProduitMedical (Id)
ALTER TABLE EffetIndesirable_ProduitMedical ADD CONSTRAINT FK_EffetIndesirable_ProduitMedical_Id_EffetIndesirable FOREIGN KEY (Id_EffetIndesirable) REFERENCES EffetIndesirable (Id)
ALTER TABLE Medicament_SubstanceActive ADD CONSTRAINT FK_Medicament_SubstanceActive_Id_SubstanceActive FOREIGN KEY (Id_SubstanceActive) REFERENCES SubstanceActive (Id)
ALTER TABLE Medicament_SubstanceActive ADD CONSTRAINT FK_Medicament_SubstanceActive_Id_Medicament FOREIGN KEY (Id_Medicament) REFERENCES ProduitMedical (Id)
ALTER TABLE Patient_ProduitMedical ADD CONSTRAINT FK_Patient_ProduitMedical_Id_ProduitMedical FOREIGN KEY (Id_ProduitMedical) REFERENCES ProduitMedical (Id)
ALTER TABLE Patient_ProduitMedical ADD CONSTRAINT FK_Patient_ProduitMedical_Id_Patient FOREIGN KEY (Id_Patient) REFERENCES Utilisateur (Id)
ALTER TABLE Ingredient_ProduitCosmetique ADD CONSTRAINT FK_Ingredient_ProduitCosmetique_Id_Ingredient FOREIGN KEY (Id_Ingredient) REFERENCES Ingredient (Id)
ALTER TABLE Ingredient_ProduitCosmetique ADD CONSTRAINT FK_Ingredient_ProduitCosmetique_Id_ProduitCosmetique FOREIGN KEY (Id_ProduitCosmetique) REFERENCES ProduitMedical (Id)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
