ALTER TABLE CENTRE DROP CONSTRAINT FK_CENTRE_Id
ALTER TABLE ClasseChimique DROP CONSTRAINT FK_ClasseChimique_mere
ALTER TABLE ClassePharmacologique DROP CONSTRAINT FK_ClassePharmacologique_mere
ALTER TABLE Departement DROP CONSTRAINT FK_Departement_Centre
ALTER TABLE EffetIndesirable DROP CONSTRAINT FK_EffetIndesirable_pere
ALTER TABLE LABORATOIRE DROP CONSTRAINT FK_LABORATOIRE_Id
ALTER TABLE MEDECIN DROP CONSTRAINT FK_MEDECIN_Id
ALTER TABLE ProduitMedical DROP CONSTRAINT FK_ProduitMedical_laboratoire
ALTER TABLE MEDICAMENT DROP CONSTRAINT FK_MEDICAMENT_Id
ALTER TABLE PATIENT DROP CONSTRAINT FK_PATIENT_Id
ALTER TABLE Declaration DROP CONSTRAINT FK_Declaration_EffetIndesirable
ALTER TABLE Declaration DROP CONSTRAINT FK_Declaration_Utilisateur
ALTER TABLE Declaration DROP CONSTRAINT FK_Declaration_ProduitMedical
ALTER TABLE DISPOSITIFMEDICAL DROP CONSTRAINT FK_DISPOSITIFMEDICAL_Id
ALTER TABLE PRODUITCOSMETIQUE DROP CONSTRAINT FK_PRODUITCOSMETIQUE_Id
ALTER TABLE ClasseChimique_EffetIndesirable DROP CONSTRAINT FK_ClasseChimique_EffetIndesirable_Id_Id_EffetIndesirable
ALTER TABLE ClasseChimique_EffetIndesirable DROP CONSTRAINT FK_ClasseChimique_EffetIndesirable_Id_ClasseChimique
ALTER TABLE ClasseChimique_SubstanceActive DROP CONSTRAINT FK_ClasseChimique_SubstanceActive_Id_SubstanceActive
ALTER TABLE ClasseChimique_SubstanceActive DROP CONSTRAINT FK_ClasseChimique_SubstanceActive_Id_ClasseChimique
ALTER TABLE ClassePharmacologique_EffetIndesirable DROP CONSTRAINT ClassePharmacologique_EffetIndesirable_Id_ClassePharmacologique
ALTER TABLE ClassePharmacologique_EffetIndesirable DROP CONSTRAINT ClassePharmacologique_EffetIndesirable_Id_Id_EffetIndesirable
ALTER TABLE ClassePharmacologique_SubstanceActive DROP CONSTRAINT ClassePharmacologique_SubstanceActive_Id_ClassePharmacologique
ALTER TABLE ClassePharmacologique_SubstanceActive DROP CONSTRAINT FK_ClassePharmacologique_SubstanceActive_Id_SubstanceActive
ALTER TABLE EffetIndesirable_ProduitMedical DROP CONSTRAINT FK_EffetIndesirable_ProduitMedical_Id_ProduitMedical
ALTER TABLE EffetIndesirable_ProduitMedical DROP CONSTRAINT FK_EffetIndesirable_ProduitMedical_Id_EffetIndesirable
ALTER TABLE Medicament_SubstanceActive DROP CONSTRAINT FK_Medicament_SubstanceActive_Id_SubstanceActive
ALTER TABLE Medicament_SubstanceActive DROP CONSTRAINT FK_Medicament_SubstanceActive_Id_Medicament
ALTER TABLE Patient_ProduitMedical DROP CONSTRAINT FK_Patient_ProduitMedical_Id_ProduitMedical
ALTER TABLE Patient_ProduitMedical DROP CONSTRAINT FK_Patient_ProduitMedical_Id_Patient
ALTER TABLE Ingredient_ProduitCosmetique DROP CONSTRAINT FK_Ingredient_ProduitCosmetique_Id_Ingredient
ALTER TABLE Ingredient_ProduitCosmetique DROP CONSTRAINT FK_Ingredient_ProduitCosmetique_Id_ProduitCosmetique
DROP TABLE Utilisateur CASCADE
DROP TABLE CENTRE CASCADE
DROP TABLE ClasseChimique CASCADE
DROP TABLE ClassePharmacologique CASCADE
DROP TABLE Departement CASCADE
DROP TABLE EffetIndesirable CASCADE
DROP TABLE LABORATOIRE CASCADE
DROP TABLE MEDECIN CASCADE
DROP TABLE ProduitMedical CASCADE
DROP TABLE MEDICAMENT CASCADE
DROP TABLE PATIENT CASCADE
DROP TABLE SubstanceActive CASCADE
DROP TABLE Declaration CASCADE
DROP TABLE DISPOSITIFMEDICAL CASCADE
DROP TABLE Ingredient CASCADE
DROP TABLE PRODUITCOSMETIQUE CASCADE
DROP TABLE ClasseChimique_EffetIndesirable CASCADE
DROP TABLE ClasseChimique_SubstanceActive CASCADE
DROP TABLE ClassePharmacologique_EffetIndesirable CASCADE
DROP TABLE ClassePharmacologique_SubstanceActive CASCADE
DROP TABLE EffetIndesirable_ProduitMedical CASCADE
DROP TABLE Medicament_SubstanceActive CASCADE
DROP TABLE Patient_ProduitMedical CASCADE
DROP TABLE Ingredient_ProduitCosmetique CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
